# Generated by Django 5.2.7 on 2025-12-04 01:02

import apps.cliente.validators.cpf_cnpj_validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cnpj', 'Pessoa Juridica'), ('cpf', 'Pessoa Fisica')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[apps.cliente.validators.cpf_cnpj_validators.validate_cpf], verbose_name='CPF')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_fisica', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Pessoa Fisica',
                'verbose_name_plural': 'Pessoas Fisica',
                'db_table': 'pessoa_fisica',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=250, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[apps.cliente.validators.cpf_cnpj_validators.validate_cnpj], verbose_name='CNPJ')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_juridica', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Pessoa Juridica',
                'verbose_name_plural': 'Pessoas Juridica',
                'db_table': 'pessoa_juridica',
                'ordering': ['razao_social'],
            },
        ),
    ]
