# Generated by Django 5.2.8 on 2025-12-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO', models.CharField(choices=[('cnpj', 'Pessoa Juridica'), ('cpf', 'Pessoa Fisica')], max_length=10)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('DATA_CRIACAO', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['DATA_CRIACAO'],
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=250)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('CLIENTE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pessoa_fisica', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Pessoa Fisica',
                'verbose_name_plural': 'Pessoas Fisica',
                'db_table': 'PESSOA_FISICA',
                'ordering': ['NOME'],
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAZAO_SOCIAL', models.CharField(max_length=250)),
                ('CNPJ', models.CharField(max_length=18, unique=True)),
                ('CLIENTE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pessoa_juridica', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Pessoa Juridica',
                'verbose_name_plural': 'Pessoas Juridica',
                'db_table': 'PESSOA_JURIDICA',
                'ordering': ['RAZAO_SOCIAL'],
            },
        ),
    ]
