# Generated by Django 5.2.7 on 2025-11-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=250)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('tipo', models.CharField(choices=[('cnpj', 'Pessoa Juridica'), ('cpf', 'Pessoa Fisica')], max_length=10)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
