# Generated by Django 5.2.7 on 2025-12-04 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=100, verbose_name='Departamento')),
                ('STATUS', models.BooleanField(default=True, verbose_name='Status')),
                ('DESCRICAO', models.TextField(verbose_name='Descricao')),
                ('DATA_CRIACAO', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('DATA_ATUALIZACAO', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('DEPARTAMENTO_PAI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamento_pai', to='departamento.departamento', verbose_name='Departamento Pai')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'DEPARTAMENTO',
                'ordering': ['NOME'],
            },
        ),
    ]
